
TRUNCATE TABLE Voiture RESTART IDENTITY CASCADE;
TRUNCATE TABLE Reservation RESTART IDENTITY CASCADE;
TRUNCATE TABLE Utilisation_voiture RESTART IDENTITY CASCADE;
TRUNCATE TABLE Hotel RESTART IDENTITY CASCADE;
TRUNCATE TABLE Distance RESTART IDENTITY CASCADE;
TRUNCATE TABLE Parametre RESTART IDENTITY CASCADE; 